version: "3.8"
services: 
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - MSSQL_DATABASE=master
      - MSSQL_SA_PASSWORD=Hola123.
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433    
  flyway:
    container_name: flyway
    image: flyway/flyway
    command:
      - "-url=jdbc:sqlserver://mssql:1433;databaseName=master;encrypt=false"
      - "-user=SA"
      - "-password=Hola123."
      - "-connectRetries=60"
      - "migrate"
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - mssql
  api-nest:
    container_name: apii-nest
    build:
     dockerfile: ./apps/api-nest/Dockerfile
    ports:
      - "3000:3000" # Expose port 3000 to the host
    volumes:
      - /apps/api-nest/app # Mount the app directory inside the container
    depends_on:
      - flyway
  app-movie:
    container_name: appp-movie
    build:
      dockerfile: ./apps/app-movie/Dockerfile
    ports:
      - "4200:4200" # Expose port 4200 to the host
    volumes:
      - /apps/app-movie/app # Mount the app directory inside the container


